//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMovieNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public int Note { get; set; }
    
        public virtual User User { get; set; }
        public virtual Movie Movie { get; set; }

        public override string ToString()
        {
            return "Comment - " +
                " ID: " + this.Id +
                " Note: " + this.Note +
                " Message: " + this.Message +
                " - ";
        }

        public override bool Equals(object obj)
        {
            bool check = false;
            if (obj.GetType() == this.GetType())
            {
                Comment param = (Comment)obj;
                check = true;
                check = check && param.Message == this.Message;
                check = check && param.Note == this.Note;
                check = check && param.User.Equals(this.User);
                check = check && param.Movie.Equals(this.Movie);
            }
            return check;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}
