//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelMovieNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }

        public override string ToString()
        {
            string comments = " -- ";
            foreach (Comment comment in this.Comments)
            {
                comments += " - " + comment.ToString() + " - ";
            }
            comments += " -- ";
            return "User - " +
                " ID: " + this.Id +
                " Login: " + this.Login +
                " Password: " + this.Password +
                " Firstname " + this.Firstname +
                " Lastname " + this.Lastname +
                " Comments " + comments +
                " - ";
        }

        public override bool Equals(object obj)
        {
            bool check = false;
            if (obj.GetType() == this.GetType())
            {
                User param = (User)obj;
                check = true;
                check = check && param.Firstname == this.Firstname;
                check = check && param.Lastname == this.Lastname;
                check = check && param.Login == this.Login;
                check = check && param.Password == this.Password;
            }
            return check;
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}
